### ISSUE TITLE
Got error when running "make installdb"

### ISSUE THREAD

**Issue by daisq94** [Ideonella-sakaiensis/lib_mysqludf_redis#4]
I enter the mysql and input these words following:
mysql>  CREATE FUNCTION `redis` RETURNS STRING SONAME 'lib_mysqludf_redis.so';
The error message is "can't find symbol redis in library". But the flag of redis is T when i runned "nm lib_mysqludf_redis.so ". I don't know what caused this error.

**Comment by wilhelmliao** [comment]
I guess your `lib_mysqludf_redis.so` don't be placed in your mysql plugin folder. You can use `mysql_config --plugindir` find the location. The location should include `lib_mysqludf_redis.so` and these dependency libraries:
- libcjson.so
- libcjson.so.1
- libcjson.so.1.6.0
- libhiredis.a
- libhiredis.so
- libhiredis.so.0.13
- lib_mysqludf_redis.so

If files are missing, you can check your <source_code_folder>/lib to find them. Then copy these to mysql plugin folder.

**Comment by daisq94** [comment]
Thank you so much.
